/**
 * Supabase Database Types
 *
 * These types tell TypeScript what tables exist in our Supabase database
 * and what columns each table has. This provides type safety when
 * querying the database.
 *
 * In a production app, you'd typically generate these types automatically
 * using: npx supabase gen types typescript
 * But for learning, we're defining them manually.
 *
 * Structure explanation:
 * - Database: The root type containing all schemas
 * - public: The default PostgreSQL schema
 * - Tables: All tables in that schema
 * - For each table: Row (select), Insert (create), Update (modify)
 */

export type Database = {
  public: {
    Tables: {
      workouts: {
        /**
         * Row type - what you get when you SELECT from the table
         * All fields are required because they exist in every row
         */
        Row: {
          id: string // UUID auto-generated by Postgres
          created_at: string // ISO timestamp string
          exercise: string // Name of the exercise
          sets: number // Number of sets performed
          reps: number // Reps per set
          weight: number // Weight used (in lbs)
          notes: string | null // Optional notes (can be null)
        }
        /**
         * Insert type - what you provide when INSERTing a new row
         * Optional fields have ? - database generates defaults for them
         */
        Insert: {
          id?: string // Optional - Postgres generates UUID
          created_at?: string // Optional - defaults to now()
          exercise: string // Required
          sets: number // Required
          reps: number // Required
          weight: number // Required
          notes?: string | null // Optional
        }
        /**
         * Update type - what you can provide when UPDATEing a row
         * All fields optional since you might only update some
         */
        Update: {
          id?: string
          created_at?: string
          exercise?: string
          sets?: number
          reps?: number
          weight?: number
          notes?: string | null
        }
      }
    }
    Views: Record<string, never> // No views defined
    Functions: Record<string, never> // No custom functions
    Enums: Record<string, never> // No custom enums
    CompositeTypes: Record<string, never> // No composite types
  }
}

/**
 * Convenience type aliases
 * These make it easier to reference types throughout the app
 */
export type Workout = Database['public']['Tables']['workouts']['Row']
export type WorkoutInsert = Database['public']['Tables']['workouts']['Insert']
export type WorkoutUpdate = Database['public']['Tables']['workouts']['Update']
